apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/telman-devops/k00s'
    path: argocd/01-manifests/main
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy: { }
